/* CVS $Id: $ */
package de.hpi.patchr.vocab; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ./vocabulary/guo.ttl 
 * @author Auto-generated by schemagen on 30 Jan 2015 16:03 
 */
public class GuoOntology {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://webr3.org/owl/guo#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Revision: 0.02";
    
    /** <p>The delete property defines blank node or resource whose predicate and object 
     *  values will be used to remove triples { target_subject predicate object } 
     *  from target_graph(s) if specified</p>
     */
    public static final Property delete = m_model.createProperty( "http://webr3.org/owl/guo#delete" );
    
    /** <p>The insert property defines a blank node or resource whose predicate and object 
     *  values will be used to create new triples inside target_graph(s) if specified 
     *  with target_subject</p>
     */
    public static final Property insert = m_model.createProperty( "http://webr3.org/owl/guo#insert" );
    
    /** <p>The merge property defines a graph from which all triples should be merged 
     *  in to the target_graph(s), unlike insert which works on a resource level rewriting 
     *  subjects, merge works on a graph level where all triples are added "as is".</p>
     */
    public static final Property merge = m_model.createProperty( "http://webr3.org/owl/guo#merge" );
    
    /** <p>Optional property of an UpdateInstruction which allows updates to apply only 
     *  to the specified Named Graph(s)</p>
     */
    public static final Property target_graph = m_model.createProperty( "http://webr3.org/owl/guo#target_graph" );
    
    /** <p>the target_subject is a required property of all UpdateInstructions which 
     *  specify an insert/delete statement, target_subject is combined with the predicate 
     *  and object values from insert/delete nodes to form triples which are to be 
     *  either inserted or deleted (optionally constrained to one or more target_graphs)</p>
     */
    public static final Property target_subject = m_model.createProperty( "http://webr3.org/owl/guo#target_subject" );
    
    /** <p>The class of an RDF Update Instruction, an UpdateInstruction defines a instructions 
     *  to be carried out by a GUO processor.</p>
     */
    public static final Resource UpdateInstruction = m_model.createResource( "http://webr3.org/owl/guo#UpdateInstruction" );
    
}
