/* CVS $Id: $ */
package de.hpi.patchr.vocab; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from ./vocabulary/patchr.ttl 
 * @author Auto-generated by schemagen on 11 Mrz 2014 14:53 
 */
public class PatchrOntology {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://purl.org/hpi/patchr#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "Revision: 0.4";
    
    /** <p>Links agents who support, i.e. like, a Patch. Each time a user creates an 
     *  patch request, appropriate provenance information is generated.</p>
     */
    public static final Property advocate = m_model.createProperty( "http://purl.org/hpi/patchr#advocate" );
    
    /** <p>Refers to a void:Dataset, to allow convenient selection of patches per data 
     *  set.</p>
     */
    public static final Property appliesTo = m_model.createProperty( "http://purl.org/hpi/patchr#appliesTo" );
    
    /** <p>A comment on the patch. This is likely just an informal message a user wants 
     *  to share when submitting a Patch.</p>
     */
    public static final Property comment = m_model.createProperty( "http://purl.org/hpi/patchr#comment" );
    
    /** <p>A confidence assigned by the creator of the patch, e.g. in case heuristic 
     *  methods identified an inconsistency. Should be in range [0,1].</p>
     */
    public static final Property confidence = m_model.createProperty( "http://purl.org/hpi/patchr#confidence" );
    
    /** <p>Links agents who disagree with the purpose of this patch.</p> */
    public static final Property criticiser = m_model.createProperty( "http://purl.org/hpi/patchr#criticiser" );
    
    /** <p>Relates a Patch to a PatchGroup. A Patch may be part of multiple PatchGroups.</p> */
    public static final Property memberOf = m_model.createProperty( "http://purl.org/hpi/patchr#memberOf" );
    
    /** <p>Refers to a classification of the patch. There might be patch taxonomies from 
     *  different applications that define the reason for a Patch on their own. A 
     *  Patch may have multiple types.</p>
     */
    public static final Property patchType = m_model.createProperty( "http://purl.org/hpi/patchr#patchType" );
    
    /** <p>Links a resource to the PatchR instance responsible for collecting patch requests.</p> */
    public static final Property patchrService = m_model.createProperty( "http://purl.org/hpi/patchr#patchrService" );
    
    /** <p>Refers to the provenance-context where this patch was created. Deprecated, 
     *  use prov:wasGeneratedBy instead.</p>
     */
    public static final Property provenance = m_model.createProperty( "http://purl.org/hpi/patchr#provenance" );
    
    /** <p>The status of the patch, might be "resolved" or "open".</p> */
    public static final Property status = m_model.createProperty( "http://purl.org/hpi/patchr#status" );
    
    /** <p>Refers to a guo:UpdateInstruction. There can be only one UpdateInstruction 
     *  per Patch.</p>
     */
    public static final Property update = m_model.createProperty( "http://purl.org/hpi/patchr#update" );
    
    /** <p>A patch is a request to add, change or delete certain triples within a dataset. 
     *  A patch refers to an guo:UpdateInstruction. For convenient retrieval a patch 
     *  should be described with provenance data, a patch type and a data set it applies 
     *  to.</p>
     */
    public static final Resource Patch = m_model.createResource( "http://purl.org/hpi/patchr#Patch" );
    
    /** <p>A patch group is a collection of patches that may apply for a common problem, 
     *  represents patches of certain users or are classified by arbitrary criteria.</p>
     */
    public static final Resource PatchGroup = m_model.createResource( "http://purl.org/hpi/patchr#PatchGroup" );
    
}
